<?php
namespace AppBundle\Repository;

use AppBundle\Entity\Questions;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{

    public function findRandom()
    {
        $ids = $this->createQueryBuilder('a')
            ->select('a.id')
            ->getQuery()
            ->getArrayResult();

        $rand = array_rand($ids);

        return $this->find($rand);
    }

    public function findRandomAnsList($correctAnswerId)
    {
        $correctAnswer = $this->find($correctAnswerId);
        $randomAnswer1 = $this->findRandom();

        if ($randomAnswer1->getId() === $correctAnswerId) {
            $randomAnswer1 = $this->findRandom();
        }

        do {
            $randomAnswer2 = $this->findRandom();
        } while ($randomAnswer1->getId() === $randomAnswer2->getId() || $randomAnswer2 === $correctAnswerId);

        $answerList = [$correctAnswer, $randomAnswer1, $randomAnswer2];
        shuffle($answerList);
        
        return $answerList;
    }
}
